services:
  wordpress:
    image: wordpress:latest
    restart: unless-stopped
    ports:
      - "80"
    labels:
      - traefik.enable=true
      - traefik.http.routers.jobseekers.rule=Host(`${SITE_DOMAIN}`)
      - traefik.http.routers.jobseekers.entrypoints=websecure
      - traefik.http.routers.jobseekers.tls.certresolver=letsencrypt
      - traefik.http.services.jobseekers.loadbalancer.server.port=80
    environment:
      - WORDPRESS_DB_HOST=db
      - WORDPRESS_DB_USER=wordpress
      - WORDPRESS_DB_PASSWORD=${MYSQL_PASSWORD}
      - WORDPRESS_DB_NAME=wordpress
    volumes:
      - wordpress_core:/var/www/html
      - ../wp-content:/var/www/html/wp-content
    depends_on:
      - db

  db:
    image: mysql:8
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=wordpress
      - MYSQL_USER=wordpress
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - db:/var/lib/mysql

volumes:
  wordpress_core:
  db:
